language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t marcoshagarcia/globality -f Dockerfile.dev . 
script:
  - docker run -e CI=true marcoshagarcia/globality npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-330572646914"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
